mybot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

# Position Controllers ---------------------------------------
  back_wheel_left_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_wheel_back_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  back_wheel_right_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_wheel_back_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  axel_hinge_right_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: axel_hinge_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  axel_hinge_left_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: axel_hinge_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
